# Generated by Django 5.2.1 on 2025-05-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(blank=True, help_text='Token de acesso do Google Calendar'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='ID do calendário principal do Google', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='google_connected',
            field=models.BooleanField(default=False, help_text='Indica se a conta Google está conectada'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_refresh_token',
            field=models.TextField(blank=True, help_text='Token de refresh do Google Calendar'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Data de expiração do token do Google', null=True),
        ),
    ]
