# Generated by Django 5.2.1 on 2025-05-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_access_token_user_google_calendar_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='insper_password',
            new_name='insper_enc_password',
        ),
        migrations.AddField(
            model_name='user',
            name='insper_curso',
            field=models.CharField(blank=True, help_text='Curso do Portal Acadêmico', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='insper_matricula',
            field=models.CharField(blank=True, help_text='Matricula do Portal Acadêmico', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='insper_portal_id',
            field=models.CharField(blank=True, help_text='ID do Portal Acadêmico', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='insper_turma',
            field=models.CharField(blank=True, help_text='Turma do Portal Acadêmico', max_length=255),
        ),
    ]
